name: elecnorappflechas
description: Aplicación de Elecnor para el cálculo de flechas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.12.0
  firebase_ui_auth: ^1.9.1
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1
  google_sign_in: ^6.1.5
  url_launcher: ^6.2.1
  logger: ^2.0.2+1
  provider: ^6.0.5
  toast: ^0.3.0
  geolocator: ^10.1.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/Elecnor.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
